os:
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
before_install:
  - brew update
  - brew install libssh2
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - swift test -Xlinker -lssh2 -Xlinker -L/usr/local/lib/
